emolab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=('static/ico/favicon.ico')), name="favicon"),
    path('admin/', admin.site.urls),
    path('lablog/', include('lablog.urls')),
    path('', RedirectView.as_view(url='/lablog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

lablog/urls.py
from django.urls import path

from . import views


urlpatterns = [

    path('', views.index, name='index'),
    path('experiments/', views.ExperimentListView.as_view(), name='experiments'),
    path('experiment/<int:pk>', views.ExperimentDetailView.as_view(), name='experiment-detail'),
    path('experiment/create/', views.ExperimentCreate.as_view(), name='experiment_create'),
    path('experiment/<int:pk>/update/', views.ExperimentUpdate.as_view(), name='experiment_update'),
    path('experiment/<int:pk>/delete/', views.ExperimentDelete.as_view(), name='experiment_delete'),

    path('subjects/', views.SubjectListView.as_view(), name='subjects'),
    path('subject/<int:pk>', views.SubjectDetailView.as_view(), name='subject-detail'),
    path('subject/create/', views.SubjectCreate.as_view(), name='subject_create'),
    path('subject/<int:pk>/update/', views.SubjectUpdate.as_view(), name='subject_update'),
    path('subject/<int:pk>/delete/', views.SubjectDelete.as_view(), name='subject_delete'),

    path('records/', views.RecordListView.as_view(), name='records'),
    path('records/', views.RecordsAllListView.as_view(), name='all-records'),
    path('record/<int:pk>', views.RecordDetailView.as_view(), name='record-detail'),
    path('record/<int:pk>/delete/', views.RecordDelete.as_view(), name='record_delete'),

    path('stimulaes/', views.StimulaeListView.as_view(), name='stimulaes'),
    path('stimulae/<int:pk>', views.StimulaeDetailView.as_view(), name='stimulae-detail'),
    path('stimulae/create/', views.StimulaeCreate.as_view(), name='stimulae_create'),
    path('stimulae/<int:pk>/update/', views.StimulaeUpdate.as_view(), name='stimulae_update'),
    path('stimulae/<int:pk>/delete/', views.StimulaeDelete.as_view(), name='stimulae_delete'),

    path('feedbacks/', views.FeedbackListView.as_view(), name='feedbacks'),
    path('feedback/<int:pk>', views.FeedbackDetailView.as_view(), name='feedback-detail'),
    path('feedback/create/', views.FeedbackCreate.as_view(), name='feedback_create'),
    path('feedback/<int:pk>/update/', views.FeedbackUpdate.as_view(), name='feedback_update'),
    path('feedback/<int:pk>/delete/', views.FeedbackDelete.as_view(), name='feedback_delete'),

    path('analyses/', views.AnalysisListView.as_view(), name='analyses'),
    path('analysis/<int:pk>', views.AnalysisDetailView.as_view(), name='analysis-detail'),
    path('analysis/create/', views.AnalysisCreate.as_view(), name='analysis_create'),
    path('analysis/<int:pk>/update/', views.AnalysisUpdate.as_view(), name='analysis_update'),
    path('analysis/<int:pk>/delete/', views.AnalysisDelete.as_view(), name='analysis_delete'),
]

lablog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


class Stimulae(models.Model):
    """
    Model representing a stimulate description and resourse reference.
    """
    name = models.CharField(
        max_length=200,
        help_text="Enter stimulate description and resourse reference")

    media1 = models.FileField(
        default='/dev/null',
        help_text='First media file')

    media2 = models.FileField(
        default='/dev/null',
        null=True,
        help_text='Optional media file')

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular stimulae instance.
        """
        return reverse('stimulae-detail', args=[str(self.id)])


class Analysis(models.Model):
    """
    Model representing an analysis setup.
    """
    name = models.CharField(
        max_length=100,
        default='default',
        help_text='Name of analysis setup')

    A = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])
    B = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])
    C = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])
    D = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])
    H = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])
    L = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)])

    def __str__(self):
        """
        String for representing Analysis object.
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular analysis instance.
        """
        return reverse('analysis-detail', args=[str(self.id)])


class Feedback(models.Model):
    """
    Model representing a feedback arrangement.
    """
    electrode1 = models.IntegerField(
        default=1, help_text='Position of first electrode')
    electrode2 = models.IntegerField(
        default=1, help_text='Position of second electrode')
    electrode3 = models.IntegerField(
        default=1, help_text='Position of third electrode')
    electrode4 = models.IntegerField(
        default=1, help_text='Position of fourth electrode')

    analysis = models.ForeignKey(
        Analysis, on_delete=models.PROTECT,
        help_text="Select a analysis for this Feedback")

    def __str__(self):
        """
        String for representing Feedback object.
        """
        return 'Feedback {self.id} ({self.electrode1}, {self.electrode2}, {self.electrode3}, {self.electrode4}, \"{self.analysis}\")'.format(
            self=self)

    def get_absolute_url(self):
        """
        Returns the url to access a particular feedback instance.
        """
        return reverse('feedback-detail', args=[str(self.id)])


class Subject(models.Model):
    """
    Model representing test subgect.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)

    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER,
        blank=True,
        default='O',
        help_text='Subject Gender')

    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['last_name']

    def get_absolute_url(self):
        """
        Returns the url to access a particular subject instance.
        """
        return reverse('subject-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)


class Record(models.Model):
    """
    Model representing a specific record.
    """

    EEG = models.FilePathField(
        path=settings.EEGDATA_STORE_PATH,
        match=".*\.db$")
    ExperimentId = models.ForeignKey(
        'Experiment', on_delete=models.PROTECT,
        )
    SubjectId = models.ForeignKey(
        Subject, on_delete=models.PROTECT,
        )
    StartTime = models.DateTimeField(null=True, blank=True)
    StopTime = models.DateTimeField(null=True, blank=True)
    ObservationMedia1 = models.CharField(max_length=200, blank=True)
    ObservationMedia2 = models.CharField(max_length=200, blank=True)

    def get_subject(self):
        print("SubjectID:")#+subject_id)
        mySubj = Subject.objects.filter(id=self.SubjectId_id).values()[0]

        return {
                'first_name':mySubj['first_name'],
                'last_name':mySubj['last_name'],
        }

    def get_experiment(self):
        myExp = Experiment.objects.filter(records=self.id).values()[0]

        return {
                'title':myExp['title'],
                'summary':myExp['summary'],
                'stimulae_id':myExp['stimulae_id'],
                'feedback_id':myExp['feedback_id']
        }

    def get_recorddb(self):
        my_file = self.EEG.split('/')[-1:]
        return str(my_file[0])

    class Meta:
        permissions = (("can_change_status", "Set record status"),)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return "record" + str(self.id)

    def get_absolute_url(self):
        """
        Returns the url to access a particular subject instance.
        """
        return reverse('record-detail', args=[str(self.id)])



class Experiment(models.Model):
    """
    Model representing a experiment (but not a specific record).
    """
    title = models.CharField(max_length=200)
    summary = models.TextField(
        max_length=1000,
        help_text="Enter a brief description of the experiment")
    DateTime = models.DateTimeField(null=True, blank=True)
    subjects = models.ManyToManyField(Subject)
    stimulae = models.ForeignKey(
        Stimulae, on_delete=models.PROTECT,
        help_text="Select a stimulae for this experiment")
    feedback = models.ForeignKey(
        Feedback, on_delete=models.PROTECT,
        help_text="Select a feedback for this experiment")
    records = models.ManyToManyField(
        Record, blank=True, help_text="Select a records for this experiment")

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        """
        Returns the url to access a particular record.
        """
        return reverse('experiment-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

lablog/views.py
from django.shortcuts import render
from .models import Experiment, Subject, Record, Stimulae, Feedback, Analysis
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import ExperimentForm, AnalysisForm
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.core import serializers


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_experiments = Experiment.objects.count()
    num_records = Record.objects.count()
    num_subjects = Subject.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Render the HTML template index.html with the data in the context
    # variable.
    return render(
        request,
        'index.html',
        context={
            'num_experiments': num_experiments,
            'num_records': num_records,
            'num_subjects': num_subjects,
            'num_visits': num_visits},
    )


class ExperimentListView(generic.ListView):
    """
    Generic class-based view for a list of experiments.
    """
    model = Experiment
    paginate_by = 10


class ExperimentDetailView(generic.DetailView):
    """
    Generic class-based detail view for a experiment.
    """
    model = Experiment
    
    #json_serializer = serializers.get_serializer("json")()
    #subjectsIDs = json_serializer.serialize(Experiment.objects.get(), ensure_ascii=False)


class StimulaeListView(generic.ListView):
    """
    Generic class-based list view for a list of records.
    """
    model = Stimulae
    paginate_by = 10


class StimulaeDetailView(generic.DetailView):
    """
    Generic class-based list view for a list of records.
    """
    model = Stimulae


class SubjectListView(generic.ListView):
    """
    Generic class-based list view for a list of subjects.
    """
    model = Subject
    paginate_by = 10


class FeedbackListView(generic.ListView):
    """
    Generic class-based list view for a list of records.
    """
    model = Feedback
    paginate_by = 10


class FeedbackDetailView(generic.DetailView):
    """
    Generic class-based list view for a list of records.
    """
    model = Feedback


class SubjectDetailView(generic.DetailView):
    """
    Generic class-based detail view for subject.
    """
    model = Subject


class RecordListView(generic.ListView):
    """
    Generic class-based list view for a list of records.
    """
    model = Record
    paginate_by = 10


class RecordDetailView(generic.DetailView):
    """
    Generic class-based list view for a list of records.
    """
    model = Record


class RecordsAllListView(PermissionRequiredMixin, generic.ListView):
    """
    Generic class-based view listing all records. Only visible to users with can_change_status permission.
    """
    model = Record
    permission_required = 'lablog.can_change_status'
    template_name = 'lablog/record_list_all.html'
    paginate_by = 10

    def get_queryset(self):
        return Record.objects.filter(status__exact='o').order_by('due_back')


class FeedbackCreate(PermissionRequiredMixin, CreateView):
    model = Feedback
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class FeedbackUpdate(PermissionRequiredMixin, UpdateView):
    model = Feedback
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class FeedbackDelete(PermissionRequiredMixin, DeleteView):
    model = Feedback
    success_url = reverse_lazy('feedbacks')
    permission_required = 'lablog.can_change_status'


class StimulaeCreate(PermissionRequiredMixin, CreateView):
    model = Stimulae
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class StimulaeUpdate(PermissionRequiredMixin, UpdateView):
    model = Stimulae
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class StimulaeDelete(PermissionRequiredMixin, DeleteView):
    model = Stimulae
    success_url = reverse_lazy('stimulaes')
    permission_required = 'lablog.can_change_status'


class SubjectCreate(PermissionRequiredMixin, CreateView):
    model = Subject
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class SubjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Subject
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class SubjectDelete(PermissionRequiredMixin, DeleteView):
    model = Subject
    success_url = reverse_lazy('subjects')
    permission_required = 'lablog.can_change_status'


class RecordCreate(PermissionRequiredMixin, CreateView):
    model = Record
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class RecordUpdate(PermissionRequiredMixin, UpdateView):
    model = Record
    fields = '__all__'
    permission_required = 'lablog.can_change_status'


class RecordDelete(PermissionRequiredMixin, DeleteView):
    model = Record
    success_url = reverse_lazy('index')
    permission_required = 'lablog.can_change_status'


class ExperimentCreate(PermissionRequiredMixin, CreateView):
    form_class = ExperimentForm
    model = Experiment
    permission_required = 'lablog.can_change_status'


class ExperimentUpdate(PermissionRequiredMixin, UpdateView):
    form_class = ExperimentForm
    model = Experiment
    permission_required = 'lablog.can_change_status'


class ExperimentDelete(PermissionRequiredMixin, DeleteView):
    model = Experiment
    success_url = reverse_lazy('experiments')
    permission_required = 'lablog.can_change_status'


class AnalysisListView(generic.ListView):
    model = Analysis


class AnalysisDetailView(generic.DetailView):
    model = Analysis


class AnalysisCreate(CreateView):
    form_class = AnalysisForm
    model = Analysis


class AnalysisUpdate(UpdateView):
    form_class = AnalysisForm
    model = Analysis

    def form_valid(self, form):
        url = super().form_valid(form)
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)("sensors", {
            "type": "sensors.update_analysis",
            "analysis": {
                "A": self.object.A,
                "B": self.object.B,
                "C": self.object.C,
                "D": self.object.D,
                "H": self.object.H,
                "L": self.object.L
            },
            "id": self.object.id,
        })
        return url


class AnalysisDelete(DeleteView):
    model = Analysis
    success_url = reverse_lazy('analyses')

lablog/templates/lablog/analysis_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Delete Analysis</h1>
</div>

<p>Are you sure you want to delete the analysis: {{ analysis }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Experiment</h1>

<p>Are you sure you want to delete the experiment: {{ experiment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/experiment_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Experiments List</h1>
</div>

<div class="table-responsive table-striped table-hover">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>DateTime</th>
				<th>Subjects</th>
				<th>Stimulae</th>
				<th>Feedback</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for experiment in experiment_list %}
			<tr>
				<td>{{ experiment.id }}</td>
				<td>{{ experiment.title }}</td>
				<td>{{ experiment.DateTime }}</td>
				<td>
					{% for subject in experiment.subjects.all %}{{ subject.first_name}}{{subject.last_name }}, {% endfor %}
				</td>
				<td>{{ experiment.stimulae.name }}</td>
				<td>{{ experiment.feedback.analysis }}</td>
				<td>
					<a href="{% url 'experiment-detail' pk=experiment.id %}">View</a>
					{% if user.is_authenticated %}
					,<a href="{% url 'experiment_update' pk=experiment.id %}">Edit</a>,
					<a class="text-danger" href="{% url 'experiment_delete' pk=experiment.id %}">Delete</a>
					{% endif %}
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'experiment_create' %}" role="button">Register new experiment</a>
{% endif %}
{% endblock %}

lablog/templates/lablog/feedback_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Feedback</h1>

<p>Are you sure you want to delete the feedback: {{ feedback }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/feedback_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Feedback: {{feedback.id}}</h1>
    <p>Electrode 1: {{feedback.electrode1}}</p>
    <p>Electrode 2: {{feedback.electrode2}}</p>
    <p>Electrode 3: {{feedback.electrode3}}</p>
    <p>Electrode 4: {{feedback.electrode4}}</p>
    <p>Analysis: {{feedback.analysis}}</p>
{% endblock %}

lablog/templates/lablog/feedback_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Feedbacks List</h1>
</div>

<div class="table-responsive table-striped table-hover">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th>#</th>
				<th>Analysis</th>
				<th>Electrode 1</th>
				<th>Electrode 2</th>
				<th>Electrode 3</th>
				<th>Electrode 4</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for feedback in feedback_list %}
			<tr>
				<td>{{ feedback.id }}</td>
				<td>{{ feedback.analysis }}</td>
				<td>{{ feedback.electrode1 }}</td>
				<td>{{ feedback.electrode2 }}</td>
				<td>{{ feedback.electrode3 }}</td>
				<td>{{ feedback.electrode4 }}</td>
				<td>
					<a href="{% url 'feedback-detail' pk=feedback.id %}">View</a>,
					<a href="{% url 'feedback_update' pk=feedback.id %}">Edit</a>,
					<a class="text-danger" href="{% url 'feedback_delete' pk=feedback.id %}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<a class="btn btn-primary" href="{% url 'feedback_create' %}" role="button">Register new feedback</a>
{% endblock %}

lablog/templates/lablog/record_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Record</h1>

<p>Are you sure you want to delete the record: {{ record }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/record_detail_values.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Experiment: {{record.experiment.title}}</h1>
    <p><h4>UID: {{record.id}}</h4></p>
    <p><h4>Subject: {{record.subject}}</h4></p>
    <p><h4>Attendant: {{record.attendant}}</h4></p>
    <p><h4>Date: {{record.rec_date}}</h4></p>
    <p><h4>Experiment Summary:{{record.experiment.summary}}</h4></p>
<p><h4>Stimulae:{{record.experiment.display_stimulae}}</h4></p>
<p><h4>Feedback:{{record.experiment.display_feedback}}</h4></p>
<p>
<p>

<p><h4>Record LevelDB: {{record.get_recorddb}}</h4></p> 

   <!--<p>Here:{{ record.values }}</p>-->

    <div id="values">
        {% for z in record.values %}
            <p data-value-id='{{ z.pk }}'>
                <label>{{ z.name }}</label>
                <input type='range' value='{{ z.value }}' min='0' max='100'>
                <output>{{ z.value }}</output>
            </p>
        {% empty %}
            <p class="empty">No values yet.</p>
        {% endfor %}
    </div>

<script>
        $(function () {
            var ws_path =  "/stream/";
            console.log("Connecting to " + ws_path);

            var webSocketBridge = new channels.WebSocketBridge();
            webSocketBridge.connect(ws_path);
            webSocketBridge.listen();
            webSocketBridge.demultiplex('intval', function(payload, streamName) {
                console.log("And Action is " + payload.action);
                // Handle different actions
                if (payload.action == "create") {
                    // Create the new integer value
                    var content = "<p data-value-id='" + payload.pk + "'><label>" + payload.data.name + "</label> <input type='range' value='" + payload.data.value + "' min='0' max='100'><output>" + payload.data.value + "</output>";
                    $("#values").append(content);
                    // Remove empty message
                    $("#values .empty").remove();
                } else if (payload.action == "update") {
                    $("p[data-value-id=" + payload.pk + "] label").text(payload.data.name);
                    $("p[data-value-id=" + payload.pk + "] input").val(payload.data.value);
                    $("p[data-value-id=" + payload.pk + "] output").val(payload.data.value);
                } else if (payload.action == "delete") {
                    $("p[data-value-id=" + payload.pk + "]").remove();
                } else {
                    console.log("Unknown action " + payload.action);
                }
            });

            // Bind changing the slider value
            $("#values").on("change", "input", function () {
                $(this).parent().find("output").val($(this).val());
                webSocketBridge.stream('intval').send({
                    "pk": $(this).parent().attr("data-value-id"),
                    "action": "update",
                    "data": {
                        "value": $(this).val(),
                    }
                });
            });

            // Helpful debugging
            webSocketBridge.socket.addEventListener('open', function() { console.log("Connected to notification socket"); });
            webSocketBridge.socket.addEventListener('close', function() { console.log("Disconnected to notification socket"); });
        });
    </script>


{% endblock %}

lablog/templates/lablog/record_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Records made by attendane</h1>

    {% if record_list %}
    <ul>

      {% for record in record_list %} 
        <a href="{% url 'experiment-detail' record.experiment.pk %}">{{record.experiment.title}}</a>  {% if user.is_staff %}- {{ record.attendant }}{% endif %} {% if perms.lablog.can_mark_returned %}- <a href="{% url 'renew-record-librarian' record.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no records made by {{ user }}.</p>
    {% endif %}       
{% endblock %}

lablog/templates/lablog/stimulae_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Stimulae</h1>

<p>Are you sure you want to delete the stimulae: {{ stimulae }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/stimulae_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Stimulae: {{stimulae.id}}</h1>
    <p>Name: {{stimulae.name}}</p>
    <p>Mediafile1: {{stimulae.media1}}</p>
    <p>Mediafile2: {{stimulae.media2}}</p>
{% endblock %}

lablog/templates/lablog/subject_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Subject</h1>

<p>Are you sure you want to delete the sudject: {{ subject }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

lablog/templates/lablog/subject_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Subject: {{ subject }} </h1>
<p>{{subject.date_of_birth}} - {% if subject.gender %}{{subject.gender}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<hl>
<h4>Experiments</h4>

<dl>
{% for experiment in subject.experiment_set.all %}
  <dt><a href="{% url 'experiment-detail' experiment.pk %}">{{experiment}}</a> ({{experiment.record_set.all.count}})</dt>
  <dd>{{experiment.summary}}</dd>
{% endfor %}
</dl>
<hl>
<h4>Records</h4>

<p><a href=""></p>

<dl>
{% for record in subject.record_set.all %}
  <dt><a href="{% url 'record-detail' record.id %}">{{record}}</a></dt>
  <dd>Attendant: {{record.attendant}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

lablog/templates/lablog/subject_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Subjects List</h1>
</div>

<div class="table-responsive table-striped table-hover">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th>#</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Date of Birth</th>
				<th>Gender</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for subject in subject_list %}
			<tr>
				<td>{{ subject.id }}</td>
				<td>{{ subject.first_name }}</td>
				<td>{{ subject.last_name }}</td>
				<td>{{ subject.date_of_birth }}</td>
				<td>{{ subject.gender }}</td>
				<td>
					<a href="{% url 'subject-detail' pk=subject.id %}">View</a>,
					<a href="{% url 'subject_update' pk=subject.id %}">Edit</a>,
					<a class="text-danger" href="{% url 'subject_delete' pk=subject.id %}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<a class="btn btn-primary" href="{% url 'subject_create' %}" role="button">Register new subject</a>
{% endblock %}